---
title: "My Meter Readings"
author: "Moses Otieno"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    social: menu
runtime: shiny
---

```{r setup, include=FALSE, cache=TRUE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(shiny)
library(DT)
library(odbc)
library(lubridate)
library(kableExtra)


```

```{r global, include=FALSE}
#---- Import Data
kplcreadings <- read_rds("kplcreadings.rds")
kiwascoreadings <- read_rds("kiwascoreadings.rds")
```



Inputs {.sidebar}
-------------------------------------------------------------------


```{r}
 selectInput("month_read", "Select month",
                            choices = month.name,
                            selected = month(Sys.Date(), label = T,
                                             abbr = F))
selectInput("dataset", "Chooses a dataset to download",
    choices = c("KPLC", "KIWASCO"),
    selected = "KPLC")
# Button
uiOutput("downloadUI")

# Create the actual downloadButton
output$downloadUI <- renderUI( {
  downloadButton("downBtn", "Download", style = "width:100%;")
})


```



This is an application developed to help track the  
consumption of electricity and water. The meter  
readings for each item is keyed into the database  
(MySQL through Python) on a daily basis. This    
Shiny application then picks that data and analyzes  
it based on the month selected.   
The dataset can also be downloaded.

```{r }
  # Reactive value for selected dataset ----
  datasetInput <- reactive({
    switch(input$dataset,
           "KPLC" = kplcreadings,
           "KIWASCO" = kiwascoreadings)
  })

  # Downloadable csv of selected dataset ----

  output$downBtn <- downloadHandler(
    filename = function() {
      paste(input$dataset, ".csv", sep = "")
    },
    content = function(file) {
      write.csv(datasetInput(), file, row.names = FALSE)
    }
  )
```

KPLC 
======

Column {data-width=350}
--------------------------------------------------------------------

Row {.tabset}
-------------------------------------------------------------------

### Raw Data
```{r}
kplcdata1 <- reactive({
    kplcreadings %>%
      arrange(desc(entry_date)) %>% 
      filter(month_read %in% input$month_read) %>% 
      select(-entry_date, -source) %>% 
      select(date_read , everything())
  })

renderDataTable(kplcdata1())
```

### Graph

```{r kplcgraph}
kplcdata <- reactive({
    kplcreadings %>%
      filter(month_read %in% input$month_read)
  })



renderPlotly({
    if(input$month_read %in% kplcdata()$month_read){
      ggplot(kplcdata(), aes(entry_date, units_perday)) +
      geom_point() +
      geom_line() +
      ggtitle(paste("Distribution of units in ", input$month_read))

    }else{
      ggplot(kplcdata(), aes(entry_date, units_perday)) +
        ggtitle(paste("No data for", input$month_read))
    }
  })



```


### Summary on consumption
#### Monthly summary
Below is the daily summary of electricity consumption in the month of `r renderText(input$month_read)`
```{r}
renderPrint(summary(kplcdata()$units_perday))
renderText(paste("The sum total of consumption as at  ", max(kplcdata()$date_read, na.rm = T) ,"is",sum(kplcdata()$units, na.rm = T)))

renderText(paste("Expected to pay", sum(kplcdata()$units, na.rm = T) * 18))

```


#### Top five days 

```{r}
tableOutput("kplctop")


#knitr::kable(kplcreadings %>%  slice_max(units_perday, n = 5))

   output$kplctop <- function() {
     kplcreadings %>%
       filter(month_read %in% input$month_read) %>%
       mutate(day_read = weekdays(entry_date)) %>% 
       select(-month_read, -source, -entry_date) %>% 
       select(date_read, day_read, reading, units, daydiff, units_perday, everything()) %>% 
       slice_max(units_perday, n = 5) %>% 
       knitr::kable("html") %>%
       kable_styling("striped", full_width = T) 
   }

```


### Yearly consumption

```{r }
kplcdata2 <- reactive({
    kplcreadings %>%
      group_by(month_read) %>% 
      summarise(monthlyunits = sum(units_perday, na.rm = TRUE),
                sdunits = sd(units_perday, na.rm = TRUE))
  })

renderPlotly(kplcdata2() %>% ggplot(aes(month_read, monthlyunits, group=1)) + geom_point() + geom_line(color="red") + geom_errorbar(aes(ymin=monthlyunits-sdunits, ymax=monthlyunits+sdunits), width=.1))


```


KIWASCO 
======

Column {data-width=350}
--------------------------------------------------------------------

Row {.tabset}
-------------------------------------------------------------------

### Raw Data
```{r}
kiwascodata1 <- reactive({
    kiwascoreadings %>%
      arrange(desc(entry_date)) %>% 
      filter(month_read %in% input$month_read) %>% 
      select(-entry_date, -source) %>% 
      select(date_read, everything())
  })


renderDataTable(kiwascodata1())
```

### Graph

```{r}
kiwascodata <- reactive({
    kiwascoreadings %>%
      filter(month_read %in% input$month_read)
  })

renderPlotly({
    if(input$month_read %in% kiwascodata()$month_read){
      ggplot(kiwascodata(), aes(entry_date, units_perday)) +
      geom_point() +
      geom_line() +
      ggtitle(paste("Distribution of units in ", input$month_read))
    }else{
      ggplot(kiwascodata(), aes(entry_date, units_perday)) +
        ggtitle(paste("No data for", input$month_read))
    }
  })
```


### Summary on consumption
#### Monthly summary
Below is the daily summary of water consumption in the month of `r renderText(input$month_read)`

```{r}
renderPrint(summary(kiwascodata()$units_perday))
renderText(paste("The sum total of consumption as at  ", max(kiwascodata()$date_read, na.rm = T) ,"is",sum(kiwascodata()$units, na.rm = T)))

```

#### Top five days 

```{r}

tableOutput("kiwascotop")


#knitr::kable(kplcreadings %>%  slice_max(units_perday, n = 5))

   output$kiwascotop <- function() {
     kiwascoreadings %>%
       filter(month_read %in% input$month_read) %>%
       mutate(day_read = weekdays(entry_date)) %>%
       select(-month_read, -source, -entry_date) %>%
       select(date_read, day_read, reading, units, daydiff, units_perday, everything()) %>% 
       slice_max(units_perday, n = 5) %>% 
       knitr::kable("html") %>%
       kable_styling("striped", full_width = T) 
   }
```


